{
  "ignition":{"version":"2.0.0"},
  "storage":{
    "files":[{
      "filesystem":"root",
      "path":"/etc/coreos/docker-1.12",
      "contents":{"source":"data:,no%0A"}
    }]
  },
  "systemd":{
    "units":[
      {"name":"docker.socket","enabled":true},
      {"name":"containerd.service","enabled":true},
      {"name":"docker.service","enabled":true},
      {"name":"docker-tcp.socket","enabled":true,"contents":${swarm_docker_tcp_service}},
      {"name":"swarm-manager-init.service","enabled":true,"contents":${swarm_manager_init_service}},
      {"name":"var-lib-docker-swarm.mount","enabled":true,"contents":${var_lib_docker_swarm_mount}},
      {"name":"swarm-manager-data-format.service","enabled":${swarm_manager_data_format_service_enabled},"contents":${swarm_manager_data_format_service}}
    ]
  }
}
