#!/bin/bash

PROFILE_NAME=${PROFILE_NAME:-default}

access_key_id='aws_access_key_id = \"" + .AccessKeyId + "\"'
secret_access_key='aws_secret_access_key = \"" + .SecretAccessKey + "\"'
session_token='aws_session_token = \"" + .Token + "\"'
credentials="\"[${PROFILE_NAME}]\n${access_key_id}\n${secret_access_key}\n${session_token}\n\""

meta_data_url="http://169.254.169.254/latest/meta-data"
security_credentials_url="${meta_data_url}/iam/security-credentials"

wget -qO- "${security_credentials_url}/${ROLE_NAME}" | jq -r "${credentials}"
