#!/usr/bin/env python

#
# Pulls the tfstate from S3. This is called prior to running
# Terraform jobs on a build agent so that the agent has
# access to the current state of the infrastructure.
#

import boto3
from botocore.exceptions import ClientError
import argparse

parser = argparse.ArgumentParser(
    description='Pulls the tfstate from S3.')
parser.add_argument(
    '--bucket', required=True,
    help='specify the bucket where the tfstate resides')

def main():
    args = parser.parse_args()

    client = boto3.client('s3')

    try:
        response = client.get_object(
            Bucket=args.bucket,
            Key='terraform.tfstate'
        )
        with open('terraform.tfstate', 'wb') as f:
            f.write(response['Body'].read())
    except ClientError as ex:
        print('Terraform tfstate file not found. Possibly first run.')

if __name__ == '__main__':
    main()
